spring:
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  sql:
    init:
      mode: always

opentracing:
  jaeger:
    http-sender:
      url: http://localhost:14268/api/traces

activity:
  point-map:
    abcd: 20

localstack:
  host: ${LOCALSTACK_HOST:localhost}