spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

opentracing:
  jaeger:
    http-sender:
      url: http://localhost:14268/api/traces

activity:
  point-map:
    abcd: 20

localstack:
  host: ${LOCALSTACK_HOST:localhost}