spring:
  cloud:
    stream:
      function:
        definition: activity-performed-consumer
      kinesis:
        binder:
          locks:
            table: example-spring-loyalty-lock
          checkpoint:
            table: example-spring-loyalty-checkpoint
    bindings:
      activity-performed-consumer-in-0:
        consumer:
          autoStartup: true
        destination: activity-performed
        group: example-spring-loyalty
  datasource:
    url: jdbc:postgresql://\${DB_HOSTNAME}:5432/\${DB_NAME}
    username: \${DB_USERNAME}
    password: \${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

management:
  health:
    diskspace:
      enabled: true
  info:
    git:
      mode: full
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  metrics:
    tags.*:
      service: example-spring-loyalty

info:
  application:
    name: ${rootProject.name}
    version: ${version}
    jdk:
      version: \${java.version}
    spring-boot:
      version: ${springBootVersion}

opentracing:
  jaeger:
    service-name: example-spring-loyalty-api-service
    const-sampler:
      decision: true
    enable-w3c-propagation: true
    log-spans: true
  spring:
    cloud:
      jdbc:
        enabled: false

cloud:
  aws:
    region:
      static: ap-southeast-1
    stack:
      auto: false

split:
  io:
    api:
      key: \${SPLIT_API_KEY}

feature:
  flags:
    EXAMPLE_SPRING_LOYALTY_EXAMPLE_FEATURE: \${EXAMPLE_SPRING_LOYALTY_EXAMPLE_FEATURE_IS_ENABLED:false}
    EXAMPLE_SPRING_LOYALTY_FIND_USER_BY_ID: \${EXAMPLE_SPRING_LOYALTY_FIND_USER_BY_ID_IS_ENABLED:false}