version: '3'
services:
  api-service-check:
    image: openjdk:11.0.2-slim
    working_dir: /api-service
    command: ./gradlew api-service:clean api-service:check api-service:zipReports
    volumes:
      - .:/api-service
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.aws:/root/.aws
      - gradle-cache:/root/.gradle

  download-gradle-cache:
    image: amazon/aws-cli
    command: s3 sync --quiet s3://java-gradle-cache /cache/
    volumes:
      - ~/.aws:/root/.aws
      - gradle-cache:/cache

  upload-gradle-cache:
    image: amazon/aws-cli
    command: s3 sync --quiet /cache/ s3://java-gradle-cache
    volumes:
      - ~/.aws:/root/.aws
      - gradle-cache:/cache

volumes:
  gradle-cache:
