version: '3'
services:
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  smocker:
    image: thiht/smocker
    ports:
      - "9080:8080"
      - "9081:8081"
  pgweb:
    image: sosedoff/pgweb
    ports:
      - "7081:8081"
    links:
      - db:postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?sslmode=disable
    depends_on:
      - db
  jaeger-remote-storage:
    image: jaegertracing/jaeger-remote-storage
    command:
      - "--log-level=debug"
    environment:
      - SPAN_STORAGE_TYPE=memory
    ports:
      - "17271:17271"

  jaeger-collector:
    image: jaegertracing/jaeger-collector
    command:
      - "--grpc-storage.server=jaeger-remote-storage:17271"
      - "--collector.zipkin.host-port=:9411"
      - "--log-level=debug"
    ports:
      - "14269"
      - "14268:14268"
      - "14250"
      - "9411:9411"
    environment:
      - SPAN_STORAGE_TYPE=grpc-plugin
      - LOG_LEVEL=debug
    restart: on-failure
    depends_on:
      - jaeger-remote-storage

  jaeger-query:
    image: jaegertracing/jaeger-query
    command:
      - "--grpc-storage.server=jaeger-remote-storage:17271"
      - "--log-level=debug"
    ports:
      - "16686:16686"
      - "16687"
    environment:
      - SPAN_STORAGE_TYPE=grpc-plugin
    restart: on-failure
    depends_on:
      - jaeger-remote-storage
  jaeger-agent:
    image: jaegertracing/jaeger-agent
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
    restart: on-failure
    command:
      - --reporter.grpc.host-port=jaeger-collector:14250
      - --reporter.type=grpc
      - --agent.tags=deployment.environment=local
    depends_on:
      - jaeger-collector
  localstack:
    image: localstack/localstack
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-1
      - EDGE_PORT=4566
      - SERVICES=kinesis, dynamodb, s3
    healthcheck:
      test: ["CMD-SHELL", "/tmp/healthcheck-localstack.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '4566:4566'
    volumes:
      - localstack:/tmp/localstack
      - './setup-localstack.sh:/docker-entrypoint-initaws.d/setup-localstack.sh'
      - './healthcheck-localstack.sh:/tmp/healthcheck-localstack.sh'

volumes:
  localstack:
