version: '3'
services:
  check:
    image: openjdk:11.0.2-slim
    working_dir: /app
    command: ./gradlew clean check zipReports
    environment:
      GRADLE_USER_HOME: /private/.gradle
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.gradle:/private/.gradle

  upload-gradle-cache:
    image: amazon/aws-cli
    command: s3 sync --quiet gradle-cache s3://example-spring-loyalty-gradle-cache
    volumes:
      - ~/.aws:/root/.aws

volumes:
  gradle-cache:

