version: '3'
services:
  api-service-check:
    image: openjdk:11.0.2-slim
    working_dir: /api-service
    command: ./gradlew api-service:clean api-service:check api-service:zipReports
    volumes:
      - .:/api-service
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.aws:/root/.aws
      - gradle-cache:/root/.gradle
  batch-job-check:
    image: openjdk:11.0.2-slim
    working_dir: /batch-job
    command: ./gradlew batch-job:clean batch-job:check batch-job:zipReports
    volumes:
      - .:/batch-job
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.aws:/root/.aws
      - gradle-cache:/root/.gradle
  api-service-build-push-docker:
    image: openjdk:11.0.2-slim
    working_dir: /api-service
    command: ./gradlew api-service:compileJava api-service:docker -PdockerUsername=$$DOCKER_USERNAME -PdockerPassword=$$DOCKER_PASSWORD
    environment:
      DOCKER_USERNAME: ${DOCKER_USERNAME}
      DOCKER_PASSWORD: ${DOCKER_PASSWORD}
    volumes:
      - .:/api-service
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.aws:/root/.aws
      - gradle-cache:/root/.gradle
volumes:
  gradle-cache:
    external: true
