version: '3'
services:
  check:
    image: openjdk:11.0.2-slim
    working_dir: /app
    command: ./gradlew clean check zipReports
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - gradle-cache:/root/.gradle

  upload-gradle-cache:
    image: mesosphere/aws-cli
    command: s3 sync --quiet /gradle-cache s3://example-spring-loyalty-gradle-cache
    volumes:
      - ~/.aws:/root/.aws
      - gradle-cache:./gradle-cache
