apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "example-spring-loyalty-api-service.fullname" . }}
  labels:
  {{- include "example-spring-loyalty-api-service.labels" . | nindent 4 }}
data:
  application.yaml: |-
    {{- if .Values.configmap }}
    {{- .Values.configmap | nindent 4 }}
  {{- end }}