apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "example-spring-loyalty.fullname" . }}
  labels:
    {{- include "example-spring-loyalty.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
      - pods
    verbs:
      - get
      - watch
      - list
