zonky:
  test:
    database:
      postgres:
        docker:
          image: postgres:alpine

cloud:
  aws:
    region:
      static: ap-southeast-1
    stack:
      auto: false

activity:
  point-map:
    abcd: 20