zonky:
  test:
    database:
      postgres:
        docker:
          image: postgres:alpine

cloud:
  aws:
    region:
      static: ap-southeast-1
    stack:
      auto: false

activity:
  point-map:
    abcd: 20

split:
  io:
    api:
      key: xxx

feature:
  flags:
    EXAMPLE_SPRING_LOYALTY_EXAMPLE_FEATURE: false
    EXAMPLE_SPRING_LOYALTY_FIND_USER_BY_ID: false