spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    enabled: false
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

cloud:
  aws:
    s3:
      bucket-name: test-bucket
    region:
      static: ap-southeast-1
    stack:
      auto: false

activity:
  point-map:
    abcd: 20

split:
  io:
    api:
      key: xxx

feature:
  flags:
    EXAMPLE_SPRING_LOYALTY_EXAMPLE_FEATURE: false
    EXAMPLE_SPRING_LOYALTY_FIND_USER_BY_ID: false