spring:
  main:
    allow-bean-definition-overriding: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  flyway:
    enabled: false
  sql:
    init:
      mode: always
zonky:
  test:
    database:
      postgres:
        docker:
          image: postgres:alpine
legacy:
  url: http://localhost:9999

cloud:
  aws:
    s3:
      bucket-name: old-loyalty-transactions
    stack:
      auto: false
