spring:
  main:
    allow-bean-definition-overriding: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    enabled: false
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

legacy:
  url: http://localhost:9999

cloud:
  aws:
    s3:
      bucket-name: old-loyalty-transactions
    stack:
      auto: false
