spring:
  main:
    allow-bean-definition-overriding: true
  batch:
    initialize-schema: always
zonky:
  test:
    database:
      postgres:
        docker:
          image: postgres:alpine
legacy:
  url: http://localhost:9999

cloud:
  aws:
    s3:
      bucket-name: old-loyalty-transactions
    stack:
      auto: false
